#!/bin/bash

# Check for merge conflicts

conflicts=`git diff --cached --name-only -G"<<<<<|=====|>>>>>" -- ':(exclude)*.md'`

if [[ -n "$conflicts" ]]; then
  echo
  echo "Unresolved merge conflicts in these files:"

  for conflict in $conflicts; do
    echo $conflict
  done;

  exit 1;
fi

exit 0
