disabled_rules:
  # Idiomatic
  # ------------------------------------------------------
  # - block_based_kvo
  # - duplicate_imports
  # - for_where
  # - force_cast
  # - force_try
  # - generic_type_name
  # - is_disjoint
  # - legacy_cggeometry_functions
  # - legacy_constant
  # - legacy_constructor
  # - legacy_hashing
  # - legacy_nsgeometry_functions
  - legacy_random
  # - no_fallthrough_only
  # - private_over_fileprivate
  # - redundant_objc_attribute
  # - redundant_optional_initialization
  # - redundant_set_access_control
  # - redundant_string_enum_value
  # - redundant_void_return
  # - syntactic_sugar
  # - trailing_semicolon
  # - type_name
  # - unavailable_condition
  # - unneeded_break_in_switch
  # - unused_enumerated
  # - void_function_in_ternary
  # - xctfail_message

  # Lint
  # ------------------------------------------------------
  # - class_delegate_protocol
  # - comment_spacing
  # - compiler_protocol_init
  # - deployment_target
  # - discouraged_direct_init
  # - duplicate_enum_cases
  # - duplicated_key_in_dictionary_literal
  # - dynamic_inline
  # - inert_defer
  # - mark
  # - notification_center_detachment
  # - nsobject_prefer_isequal
  # - orphaned_doc_comment
  # - private_unit_test
  # - self_in_property_initialization
  # - superfluous_disable_command
  # - todo
  # - unused_capture_list
  # - unused_closure_parameter
  # - unused_control_flow_label
  # - unused_setter_value
  # - valid_ibinspectable

  # Metrics
  # ------------------------------------------------------
  # - cyclomatic_complexity
  # - file_length
  # - function_body_length
  # - function_parameter_count
  # - large_tuple
  - line_length
  # - nesting
  # - type_body_length

  # Performance
  # ------------------------------------------------------
  # - reduce_boolean

  # Style
  # ------------------------------------------------------
  # - closing_brace
  # - closure_parameter_position
  # - colon
  # - comma
  - comma_inheritance
  # - computed_accessors_order
  # - control_statement
  # - empty_enum_arguments
  # - empty_parameters
  # - empty_parentheses_with_trailing_closure
  - identifier_name
  # - implicit_getter
  # - inclusive_language
  # - leading_whitespace
  # - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  # - opening_brace
  # - operator_whitespace
  # - protocol_property_accessors_order
  # - redundant_discardable_let
  # - return_arrow_whitespace
  # - shorthand_operator
  # - statement_position
  # - switch_case_alignment
  # - trailing_comma
  # - trailing_newline
  # - trailing_whitespace
  # - unused_optional_binding
  # - vertical_parameter_alignment
  # - vertical_whitespace
  - void_return

opt_in_rules:
  # Idiomatic
  # ------------------------------------------------------
  # - anonymous_argument_in_multiline_closure
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  # - discouraged_optional_collection
  # - explicit_acl
  # - explicit_enum_raw_value
  # - explicit_init
  # - explicit_top_level_acl
  # - explicit_type_interface
  # - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name
  - file_name_no_space
  # - force_unwrapping
  # - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - legacy_multiple
  # - legacy_objc_type
  # - nimble_operator
  # - no_extension_access_modifier
  # - no_grouping_extension
  - object_literal
  # - pattern_matching_keywords
  # - prefer_nimble
  # - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - static_operator
  # - strict_fileprivate
  - toggle_bool
  - unavailable_function
  - untyped_error_in_catch
  # - xct_specific_matcher

  # Lint
  # ------------------------------------------------------
  # - accessibility_label_for_image
  - anyobject_protocol
  - array_init
  # - balanced_xctest_lifecycle
  - discarded_notification_center_observer
  # - empty_xctest_method
  # - expiring_todo
  - ibinspectable_in_extension
  - identical_operands
  - lower_acl_than_parent
  - missing_docs
  # - nslocalizedstring_key
  # - nslocalizedstring_require_bundle
  - overridden_super_call
  - override_in_extension
  - private_action
  # - private_outlet
  # - private_subject
  # - prohibited_interface_builder
  - prohibited_super_call
  # - quick_discouraged_call
  # - quick_discouraged_focused_test
  # - quick_discouraged_pending_test
  # - raw_value_for_camel_cased_codable_enum
  # - required_deinit
  # - required_enum_case
  - strong_iboutlet
  # - test_case_accessibility
  # - unowned_variable_capture
  # - weak_delegate
  - yoda_condition

  # Metrics
  # ------------------------------------------------------
  # - closure_body_length
  # - enum_case_associated_values_count

  # Performance
  # ------------------------------------------------------
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - reduce_into
  - sorted_first_last

  # Style
  # ------------------------------------------------------
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  # - file_header
  - file_types_order
  - implicit_return
  # - indentation_width
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  # - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  # - optional_enum_case_matching
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  # - prefixed_toplevel_constant
  # - single_test_class
  # - sorted_imports
  # - switch_case_on_newline
  - trailing_closure
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  # - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  # - capture_variable
  - explicit_self
  # - typesafe_array_init
  - unused_declaration
  - unused_import

# ------------------------------------------------------

# Idiomatic
# ------------------------------------------------------
conditional_returns_on_newline:
  if_only: true

discouraged_object_literal:
  color_literal: false

force_cast:
  severity: warning

force_try:
  severity: warning

object_literal:
  severity: warning
  color_literal: true
  image_literal: false

trailing_semicolon:
  severity: error

# Metrics
# ------------------------------------------------------
cyclomatic_complexity:
  warning: 15
  error: 20

file_length:
  warning: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 100
  error: 200

# Style
# ------------------------------------------------------
identifier_name:
  validates_start_with_lowercase: false
  max_length:
    warning: 100
    error: 100

  min_length:
    warning: 2
    error: 2

  allowed_symbols:
    - "_"

  excluded:
    - "x"
    - "y"
    - "z"
    - "a"
    - "b"
    - "i"
    - "j"

implicit_return:
  included: [getter, closure]

modifier_order:
  preferred_modifier_order:
    - override
    - acl
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

number_separator:
  minimum_length: 5

trailing_closure:
  only_single_muted_parameter: true

trailing_newline:
  severity: error

type_contents_order:
  order:
    - associated_type
    - type_alias
    - case
    - subtype
    - type_property
    - instance_property
    - ib_inspectable
    - ib_outlet
    - initializer
    - deinitializer
    - type_method
    - view_life_cycle_method
    - ib_action
    - other_method
    - subscript

switch_case_alignment:
  indented_cases: true

# Lint
# ------------------------------------------------------
missing_docs:
  warning: open

# Custom
# ------------------------------------------------------
custom_rules:
  final_class:
    regex: "^class [a-zA-Z\\d]+[^{]+\\{"
    message: "Classes should be marked as final whenever possible. If you actually need it to be subclassable, just add `// swiftlint:disable:this final_class`."
    severity: warning

  boolean_return:
    name: "Boolean Return"
    regex: "\\? (true : false)|(false : true)"
    message: "It is redundant to return true or false for a boolean value. Instead return the value itself."
    severity: warning

  no_nsrect:
    regex: "\\bNSRect\\b"
    match_kinds: typeidentifier
    message: "Use CGRect instead of NSRect"
    severity: warning

  no_nssize:
    regex: "\\bNSSize\\b"
    match_kinds: typeidentifier
    message: "Use CGSize instead of NSSize"
    severity: warning

  no_nspoint:
    regex: "\\bNSPoint\\b"
    match_kinds: typeidentifier
    message: "Use CGPoint instead of NSPoint"
    severity: warning

  no_cgfloat:
    regex: "\\bCGFloat\\b"
    match_kinds: typeidentifier
    message: "Use Double instead of CGFloat"
    severity: warning

  no_cgfloat2:
    regex: "\\bCGFloat\\("
    message: "Use Double instead of CGFloat"
    severity: warning

  # SwiftUI
  # ------------------------------------------------------
  swiftui_state_private:
    regex: "@(State|StateObject|ObservedObject|EnvironmentObject)\\s+var"
    message: "SwiftUI @State/@StateObject/@ObservedObject/@EnvironmentObject properties should be private"
    severity: warning

  swiftui_environment_private:
    regex: "@Environment\\(\\\\.\\w+\\)\\s+var"
    message: "SwiftUI @Environment properties should be private"
    severity: warning

  # Style
  # ------------------------------------------------------
  tabs:
    name: "Tab Whitespace"
    regex: "\\t"
    message: "Using tabs is discouraged. Use spaces only."
    severity: warning
