disabled_rules:
  - line_length
  - todo
  - force_cast

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_string
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - implicit_return
  - indentation_width
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - private_action
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strong_iboutlet
  - trailing_closure
  - unavailable_function
  - untyped_error_in_catch
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

cyclomatic_complexity:
  warning: 12
  error: 15

file_length:
  warning: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 100
  error: 200

trailing_newline:
  severity: error

trailing_comma:
  mandatory_comma: true
  severity: warning

force_try:
  severity: warning

trailing_semicolon:
  severity: error

object_literal:
  severity: warning
  color_literal: true
  image_literal: false

discouraged_object_literal:
  color_literal: false

implicit_return:
  included: [getter, closure]

trailing_closure:
  only_single_muted_parameter: true

identifier_name:
  min_length: 1

number_separator:
  minimum_length: 5

indentation_width:
  indentation_width: 2

custom_rules:
  boolean_return:
    name: "Boolean Return"
    regex: "\\? (true : false)|(false : true)"
    message: "It is redundant to return true or false for a boolean value. Instead return the value itself."
    severity: warning

  tabs:
    name: "Tab Whitespace"
    regex: "\\t"
    message: "Using tabs is discouraged. Use spaces only."
    severity: warning
