autocmd BufRead,BufNewFile .babelrc             setfiletype json
autocmd BufRead,BufNewFile .eslintrc            setfiletype json
autocmd BufRead,BufNewFile .jsbeautifyrc        setfiletype json
autocmd BufRead,BufNewFile .jscsrc              setfiletype json
autocmd BufRead,BufNewFile .jshintrc            setfiletype json
autocmd BufRead,BufNewFile .prettierrc          setfiletype json
autocmd BufRead,BufNewFile .remarkrc            setfiletype json
autocmd BufRead,BufNewFile .stylelintrc         setfiletype json
autocmd BufRead,BufNewFile .tern-{project,port} setfiletype json
